### PR TITLE
Support concept of default booleans

### PR DESCRIPTION
**Pull request by f2prateek**
updated version of #11 

Things changed:
1. Remap settings with _v2 suffix so that current SDK versions preserve existing behaviour.
2. Simplified code since constants can't be shared b/w segment and Taplytics anymore.
3. Simplified tests by removing unnecessary tests and doing more e2e testing by checking args on the Taplytics.start call.

cc @VicV

### CODE REVIEW

**Comment by VicV** [comment]
neato

**Comment by VicV** [comment]
@f2prateek let me know when these settings are also up on the website.

**Comment by f2prateek** [comment]
@VicV This is what it looks like in the UI https://cloudup.com/cyQF8H_qZuM https://cloudup.com/c5d4NloExOr

Once we add it for iOS we can consolidate the label.

I also realised we don't have any description for the live update  and turn menu options. Could you send me a description , something like this:

```
 "shakeMenu_v2": {
            "default": "default",
            "description": "This will control whether the in-app Shake Menu is enabled or not.",
            "label": "Enable Shake Menu (Android)",
            "options": [
                {
                    "text": "False",
                    "value": "false"
                },
                {
                    "text": "True",
                    "value": "true"
                },
                {
                    "text": "Default",
                    "value": "default"
                }
            ],
            "type": "select"
        }
```

**Comment by f2prateek** [comment]
Here's what they all look like for now https://cloudup.com/cqC-K-mbdw2

**Comment by VicV** [comment]
LiveUpdate:

> "description": "This will automatically flag this device as a dev device and make a socket connection to the server for testing experiments and variations live. ",

TurnMenu:

> "description": "This is an alternative method of accessing the shake menu, useful for emulators that do not have such a capability. When enabled, turning the device three times will bring up the menu",

**Comment by f2prateek** [comment]
Perfect, updated!

**Pull request merged**
